#!/bin/bash

/cave/sabi.js/scripts/GL-fast

#export MXML_HOME=/cave/calvr/jschulze/extlibs/lib
#export OSG_HOME=/cave/calvr/jschulze/extlibs/lib64
#export OSG_INCLUDE_DIR=/cave/calvr/jschulze/extlibs/include
#export CALVR_HOME=/cave/calvr/jschulze/CalVR
#export CALVR_CONFIG_FILE=monash-xinerama.xml
#export COLLADA_DIR=/cave/calvr/jschulze/extlibs
#export ITK_DIR=/cave/calvr/jschulze/extlibs/src/ITK/build
#export LD_LIBRARY_PATH=/cave/calvr/jschulze/extlibs/lib64:/cave/calvr/jschulze/extlibs/lib:/usr/local/cuda-5.5/lib64:$LD_LIBRARY_PATH

#export PATH=/cave/calvr/jschulze/CalVR/bin:/cave/calvr/jschulze/extlibs/bin:/cave/calvr/jschulze/deskvox/bin:$PATH
cd /cave/calvr/jschulze/CalVR/bin
. /usr/share/Modules/3.2.10/init/bash
module load calvr/jsch
xterm -e ./CalVR
#./CalVR
