#!/bin/sh

#tentakel scp lyra:/scratch/googleearth/myplaces.kml /scratch/googleearth

sudo googleMixed

scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/1.kml lyra-09:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/1.kml lyra-10:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/2.kml lyra-11:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/2.kml lyra-12:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/3.kml lyra-13:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/3.kml lyra-14:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/4.kml lyra-15:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/4.kml lyra-16:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/5.kml lyra-17:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/5.kml lyra-18:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/6.kml lyra-19:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/6.kml lyra-20:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/7.kml lyra-21:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/7.kml lyra-22:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/8.kml lyra-23:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/8.kml lyra-24:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/9.kml lyra-25:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/9.kml lyra-26:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/10.kml lyra-27:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/10.kml lyra-28:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/11.kml lyra-29:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/11.kml lyra-30:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/12.kml lyra-31:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/crimesPerMonth/12.kml lyra-32:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/absoluteTimezone.kml lyra-33:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/absoluteTimezone.kml lyra-34:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/absoluteTimezone.kml lyra-35:/scratch/googleearth/myplaces.kml
scp /home/evl/evldemo/CAVE2.js/kml/results/absoluteTimezone.kml lyra-36:/scratch/googleearth/myplaces.kml

