#!/bin/sh

/cave/sabi.js/scripts/GL-highperformance

#cd /data/big/dbarnes/dvohl/s2cave/encube
#python ./encube_m.py config/dany-cave-imagehd.json 0
cd /home/toand/git/s2cave_imagehd/encube
python encube_m.py config/toand-cave-imagehd-cfg.json 0
