#!/bin/bash

. /usr/share/Modules/3.2.10/init/bash
module load omegalib/13-c++11
/cave/sabi.js/scripts/GL-highperformance

cd /home/toand/git/projects/gigapoint/apps/CAVE2
xterm -e orun -s run_century.py
