#!/bin/sh

nvidia-settings --assign=":0.0/SyncToVBlank=1"
tentakel nvidia-settings --assign=":0.0/SyncToVBlank=1"
tentakel nvidia-settings --assign=":0.1/SyncToVBlank=1"

nvidia-settings --assign=":0.0/FXAA=0" --assign=":0.0/FSAA=11" --assign=":0.0/FSAAAppControlled=0" --assign=":0.0/FSAAAppEnhanced=0" --assign=":0.0/LogAniso=3" --assign=":0.0/TextureSharpen=1" --assign=":0.0/GPUPowerMizerMode=1" --assign=":0.0/OpenGLImageSettings=0"

tentakel nvidia-settings --assign=":0.0/FXAA=0" --assign=":0.0/FSAA=11" --assign=":0.0/FSAAAppControlled=0" --assign=":0.0/FSAAAppEnhanced=0" --assign=":0.0/LogAniso=3" --assign=":0.0/TextureSharpen=1" --assign=":0.0/GPUPowerMizerMode=1" --assign=":0.0/OpenGLImageSettings=0"
tentakel nvidia-settings --assign=":0.1/FXAA=0" --assign=":0.1/FSAA=11" --assign=":0.1/FSAAAppControlled=0" --assign=":0.1/FSAAAppEnhanced=0" --assign=":0.1/LogAniso=3" --assign=":0.1/TextureSharpen=1" --assign=":0.1/GPUPowerMizerMode=1" --assign=":0.1/OpenGLImageSettings=0"

