#!/bin/sh

echo "HD-1080p-HDMI"

#ssh lyra-36 killall -9 decklinkcapture jackd
killall -9 decklinkcapture jackd

#ssh lyra-36 $SAGE_DIRECTORY/bin/decklinkcapture -d 0 -m 7 -i 2 -v
$SAGE_DIRECTORY/bin/decklinkcapture -d 0 -m 9 -i 2 -v
