#!/bin/sh

/cave/sabi.js/scripts/GL-highperformance

cd /cave/Electro/cave2twaka

killall -9 cave2twaka
xterm -e "./cave2twaka track1.cave.monash.edu" &


cd /cave/Electro/examples/mars/
xterm -e ./run_monash

