#!/bin/sh

module load omegalib/4.2.4
/cave/omegalib/install/omegalib/bin/mcsend 'oexit()'
orun -K
module unload omegalib/4.2.4

module load omegalib/13-c++11
orun -K

sleep 2

killall -9 orun
tentakel killall -9 orun
tentakel "pkill -f deepzoom_tiled.py"

