#!/bin/sh
module load omegalib/4.2.4

cd /cave/omegalib/install/omegalib/bin

./orun -K

/cave/sabi.js/scripts/GL-highperformance

cd /cave/omegalib/apps/baybridge

xterm -e /cave/omegalib/install/omegalib/bin/orun -s baybridge.py


