#!/bin/sh

cd /cave/omegalib/install/omegalib/bin

./orun -K

/cave/sabi.js/scripts/GL-highperformance


cd /cave/omegalib/apps/enterprise

xterm -e /cave/omegalib/install/omegalib/bin/orun -s enterprise.py



