#!/bin/sh
module load omegalib/4.2.4 
cd /cave/omegalib/install/omegalib/bin

./orun -K

/cave/sabi.js/scripts/GL-highperformance

cd /cave/omegalib/apps/cave2surfer

xterm -e /cave/omegalib/install/omegalib/bin/orun -s c2s-kookaburra.py

