#!/bin/bash

/cave/sabi.js/scripts/PlanarCave

. /usr/share/Modules/3.2.10/init/bash
#module load omegalib/13-c++11
module load LavaVR/1.0.0
#module load anaconda
export PATH=/home/toand/git/projects/vsviewer/build/PREVIS:${PATH}
/cave/sabi.js/scripts/GL-highperformance

cd /cave/git/previs/client-script
echo $1
xterm -e python runprevis.py -s https://mivp-dws1.erc.monash.edu:3000 -d /cave/git/previs/data $1

