#!/bin/sh

export PATH=/cave/dev/node/node-v4.2.2-linux-x64/bin:${PATH}

ssh contextuwall@triohead "nohup /home/contextuwall/dev/contextuwall/ContextuWallServer/re-start_server.sh"

sleep 5
cd /data/big/dev/IA/contextuwall/ContextuWallServer
xterm -e "startServerWithSage2AndTrioRemote.sh "&
