#!/bin/bash

# replace link to imagelist file
origFile=`cat /cave/share/saver/bgfile.txt`
newFile=`/cave/share/saver/bg_black.txt`

if [ "$origFile" == "$newFile" ]; then

exit

fi

# replace link to imagelist file
unlink /cave/share/saver/bgfile.txt
ln -s /cave/share/saver/bg_mivp3d_irt_scaled.txt /cave/share/saver/bgfile.txt

# change to restart saver2 on nodes
sudo /usr/local/bin/killsaver
