#!/bin/bash

# replace link to imagelist file
origFile=`cat /cave/share/saver/bgfile.txt`
newFile=`cat /cave/share/saver/bg_fic_dark_201801.txt`

if [ "$origFile" == "$newFile" ]; then

exit

fi
# replace link to imagelist file
unlink /cave/share/saver/bgfile.txt
ln -s /cave/share/saver/bg_fic_dark_201801.txt /cave/share/saver/bgfile.txt

# change to restart saver2 on nodes
sudo /usr/local/bin/killsaver
