#!/bin/sh

/cave/sabi.js/scripts/PlanarCave

cd /cave/sabi.js/scripts/
python smarthub.py simplewindows 20x20_cave
cd /home/toand/git/projects/videocave/build

./STOP_CAVE.sh
sleep 2
./GO_CAVE2957.sh
