#!/bin/sh

#SUSE cd /home/cave/dev/videocave/build
cd /home/toand/git/projects/videocave/build
./STOP_CAVE.sh


# Stop Capture
#/cave/sabi.js/scripts/HD-STOP &
#sleep 5

# Stop SAGE
#/cave/sabi.js/scripts/SAGEOff &

