#!/bin/bash

. /usr/share/Modules/3.2.10/init/bash
module load omegalib/13-c++11
/cave/sabi.js/scripts/GL-highperformance

cd /home/toand/git/projects/tessterrain/examples/sa4overlay/CAVE
xterm -e orun -s dem_overlay_cave.py
