#!/bin/bash
/cave/sabi.js/scripts/UnityElwoodSTOP
sleep 1
cd /scratch/Unity/cluster_deployment/master/UnityCluster/uploads/f945393e0dea2ac96efaf02db90d96647c3aebdd9cc6722bd8569edd2ff8ead6/ 
./Elwood.x86_64 -server 20 tcp://*:5000 tcp://*:* -logFile server.txt -screen-fullscreen 0 &
sleep 2
tentakel /cave/Unity/cluster_deployment/master/UnityCluster/uploads/f945393e0dea2ac96efaf02db90d96647c3aebdd9cc6722bd8569edd2ff8ead6/run_client.sh
