#!/bin/sh

nvidia-settings --assign=":0.0/SyncToVBlank=0" --assign FSAA=0 --assign FSAAAppControlled=0 --assign FSAAAppEnhanced=0
tentakel nvidia-settings --assign=":0.0/SyncToVBlank=0" --assign FSAA=0 --assign FSAAAppControlled=0 --assign FSAAAppEnhanced=0

